# Generated by Django 4.1.1 on 2022-10-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unique_id',
            field=models.CharField(blank=True, default='GkJHK1tX6', editable=False, max_length=15, null=True, unique=True),
        ),
    ]
